[package]
name = "day12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.1.0"
dashmap = { version = "5.5.3", features = ["rayon"] }
rayon = "1.8.0"
